name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
-
  title: 'Features'
  labels:
  - 'feature'
  - 'enhancement'
-
  title: 'Bug Fixes'
  labels:
  - 'fix'
  - 'bugfix'
  - 'bug'
-
  title: ' Maintenance'
  label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
exclude-labels:
- 'skip-changelog'
autolabeler:
-
  label: 'bug'
  branch:
  - '/bug\/.+/'
  - '/bugfix\/.+/'
  - '/fix\/.+/'
-
  label: 'enhancement'
  branch:
  - '/(.*:)?feat\/.+/'
  - '/feature\/.+/'
  - '/enhancement\/.+/'
-
  label: 'chore'
  branch:
  - '/chore\/.+/'
  - '/maintenance\/.+/'
  - '/docs{0,1}\/.+/'
template: |
  ## What's new

  $CHANGES
