name: build multi arch

on:
  push:
    branches:
      - master

jobs:
  checksecrets:
    name: Check if repository secrets were set
    runs-on: ubuntu-latest
    outputs:
      DOCKERHUB_USERNAME: ${{ steps.dockerhub_username.is_set}}
      DOCKERHUB_TOKEN: ${{ steps.dockerhub_token.is_set }}
    steps:
    -
      name: Check whether DOCKERHUB_USERNAME is set
      id: dockerhub_username
      env:
        secret: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        echo "is_set: ${{ env.secret != '' }}"
        echo "::set-output name=is_set::${{ env.secret != '' }}"
    -
      name: Check whether DOCKERHUB_TOKEN is set
      id: dockerhub_token
      env:
        secret: ${{ secrets.DOCKERHUB_TOKENX }}
      run: |
        echo "is_set: ${{ env.secret != '' }}"
        echo "::set-output name=is_set::${{ env.secret != '' }}"

#  docker:
#    runs-on: ubuntu-latest
#    steps:
#    -
#      name: Checkout
#      uses: actions/checkout@v2
#    -
#      name: Set up QEMU
#      uses: docker/setup-qemu-action@v1
#    -
#      name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v1
#    -
#      name: Login to DockerHub
#      uses: docker/login-action@v1 
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}
#    -
#      name: Build and push
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        platforms: linux/amd64,linux/arm64
#        push: true
#        tags: psmiraglia/glowing-invention:latest
