name: build multi arch

on:
  push:
    branches:
      - master

jobs:
  check_secrets:
    name: Check whether repository secrets are set
    runs-on: ubuntu-latest
    outputs:
      DOCKERHUB_USERNAME: ${{ steps.dockerhub_username.outputs.is_set }}
      DOCKERHUB_TOKEN: ${{ steps.dockerhub_token.outputs.is_set }}
      ALL: ${{ steps.dockerhub_token.outputs.is_set && steps.dockerhub_token.outputs.is_set }}
    steps:
    -
      name: Check DOCKERHUB_USERNAME
      id: dockerhub_username
      run: |
        echo "is_set: ${{ secrets.DOCKERHUB_USERNAME != '' }}"
        echo "::set-output name=is_set::${{ secrets.DOCKERHUB_USERNAME != '' }}"
    -
      name: Check DOCKERHUB_TOKEN
      id: dockerhub_token
      run: |
        echo "is_set: ${{ secrets.DOCKERHUB_TOKEN != '' }}"
        echo "::set-output name=is_set::${{ secrets.DOCKERHUB_TOKEN != '' }}"

#  build_docker:
#    name: Build multi-arch Docker image
#    runs-on: ubuntu-latest
#    needs:
#    - check_secrets
#    steps:
#    -
#      if: ${{ needs.check_secrets.outputs.result == 'true' }}
#      name: Checkout
#      uses: actions/checkout@v2
#    -
#      if: ${{ needs.check_secrets.outputs.result == 'true' }}
#      name: Set up QEMU
#      uses: docker/setup-qemu-action@v1
#    -
#      if: ${{ needs.check_secrets.outputs.result == 'true' }}
#      name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v1
#    -
#      if: ${{ needs.check_secrets.outputs.result == 'true' }}
#      name: Login to DockerHub
#      uses: docker/login-action@v1 
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}
#    -
#      if: ${{ needs.check_secrets.outputs.result == 'true' }}
#      name: Build and push
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        platforms: linux/amd64,linux/arm64
#        push: true
#        tags: psmiraglia/glowing-invention:latest
