name: build multi arch

on:
  push:
    branches:
      - master

jobs:
  checksecrets:
    name: Check if repository secrets were set
    runs-on: ubuntu-latest
    outputs:
      DOCKERHUB_USERNAME: ${{ steps.dockerhub_username.is_set}}
      DOCKERHUB_TOKEN: ${{ steps.dockerhub_token.is_set }}
      ALL: ${{ steps.all.is_set }}
    steps:
    -
      name: Check whether DOCKERHUB_USERNAME secret is set
      id: dockerhub_username
      env:
        secret: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        echo "is_set: ${{ env.secret != '' }}"
        echo "::set-output name=is_set::${{ env.secret != '' }}"
    -
      name: Check whether DOCKERHUB_TOKEN secret is set
      id: dockerhub_token
      env:
        secret: ${{ secrets.DOCKERHUB_TOKENX }}
      run: |
        echo "is_set: ${{ env.secret != '' }}"
        echo "::set-output name=is_set::${{ env.secret != '' }}"
    -
      name: All secrets
      id: all_secrets
      run: |
        echo "is_set: ${{ secrets.DOCKEHUB_USERNAME != '' && secrets.DOCKEHUB_TOKENX != '' }}"
        echo "::set-output name=is_set::${{ secrets.DOCKEHUB_USERNAME != '' && secrets.DOCKEHUB_TOKENX != '' }}"

  build_docker:
    name: Build multi-arch Docker image
    runs-on: ubuntu-latest
    needs:
    - checksecrets
    steps:
    -
      if: needs.checksecrets.outputs.DOCKERHUB_USERNAME == 'true' && needs.checksecrets.outputs.DOCKERHUB_TOKEN == 'true'
      name: Checkout
      uses: actions/checkout@v2
    -
      if: needs.checksecrets.outputs.DOCKERHUB_USERNAME == 'true' && needs.checksecrets.outputs.DOCKERHUB_TOKEN == 'true'
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      if: needs.checksecrets.outputs.DOCKERHUB_USERNAME == 'true' && needs.checksecrets.outputs.DOCKERHUB_TOKEN == 'true'
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      if: needs.checksecrets.outputs.DOCKERHUB_USERNAME == 'true' && needs.checksecrets.outputs.DOCKERHUB_TOKEN == 'true'
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      if: needs.checksecrets.outputs.DOCKERHUB_USERNAME == 'true' && needs.checksecrets.outputs.DOCKERHUB_TOKEN == 'true'
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: psmiraglia/glowing-invention:latest
