name: build multi arch

on:
  push:
    branches:
      - master

jobs:
  checksecrets:
    name: Check id secrets were set
    runs-on: ubuntu-latest
    outputs:
      DOCKERHUB_USERNAME_is_set:
      DOCKERHUB_TOKEN_is_set:
    steps:
    -
      name: Check whether DOCKERHUB_USERNAME is set
      id: check_dockerhub_username
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKENX }}
      run: |
        echo "DOCKERHUB_USERNAME_is_set: ${{ env.DOCKERHUB_USERNAME != '' }}"
        echo "::set-output name=DOCKERHUB_USERNAME_is_set::${{ env.DOCKERHUB_USERNAME != '' }}"
        echo "DOCKERHUB_TOKEN_is_set: ${{ env.DOCKERHUB_TOKEN != '' }}"
        echo "::set-output name=DOCKERHUB_TOKEN_is_set::${{ env.DOCKERHUB_TOKEN != '' }}"
#  docker:
#    runs-on: ubuntu-latest
#    steps:
#    -
#      name: Checkout
#      uses: actions/checkout@v2
#    -
#      name: Set up QEMU
#      uses: docker/setup-qemu-action@v1
#    -
#      name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v1
#    -
#      name: Login to DockerHub
#      uses: docker/login-action@v1 
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}
#    -
#      name: Build and push
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        platforms: linux/amd64,linux/arm64
#        push: true
#        tags: psmiraglia/glowing-invention:latest
