name: Do something on new release

on:
  release:
    type:
    - published

jobs:
  doit:
    runs-on: ubuntu-latest
    steps:
    -
      name: Do It
      run: |
        echo "${{ github.event_name }} (${{ github.event.action }})"
