name: Do something on new release

on:
  release:
    types:
    - published

jobs:
  doit:
    runs-on: ubuntu-latest
    steps:
    -
      name: Do It always
      run: |
        echo "${{ github.event_name }} (${{ github.event.action }}, ${{ github.event }})"
    -
      if: ${{ github.event.release.prerelease }}
      name: Do it only when pre-released
      run: |
        echo "${{ github.event_name }} (${{ github.event.action }})"
    -
      if: ${{ !github.event.release.prerelease }}
      name: Do it only when released
      run: |
        echo "${{ github.event_name }} (${{ github.event.action }})"
