name: Do something on new release

on: release

jobs:
  doit:
    runs-on: ubuntu-latest
    steps:
    -
      name: Do It always
      run: |
        echo "${{ github.event_name }} (${{ github.event.action }})"
    -
      if: ${{ github.event.action == 'prereleased' }}
      name: Do it only when pre-released
      run: |
        echo "${{ github.event_name }} (${{ github.event.action }})"
    -
      if: ${{ github.event.action == 'released' }}
      name: Do it only when released
      run: |
        echo "${{ github.event_name }} (${{ github.event.action }})"
