name: Do something on new release

on:
  release:
    types:
    - created
    - published

jobs:
  doit:
    runs-on: ubuntu-latest
    steps:
    -
      name: Do It always
      run: |
        echo "${{ github.event_name }} (${{ github.event.action }})"
    -
      if: ${{ github.event.action == 'created' }}
      name: Do it only when created
      run: |
        echo "${{ github.event_name }} (${{ github.event.action }})"
    -
      if: ${{ github.event.action == 'published' }}
      name: Do it only when published
      run: |
        echo "${{ github.event_name }} (${{ github.event.action }})"
